// Sample set of quotes categorized by emotions
const quotes = {
    happy: [
        "Happiness is not something ready made. It comes from your own actions. - Dalai Lama",
        "For every minute you are angry you lose sixty seconds of happiness. - Ralph Waldo Emerson",
        "Happiness depends upon ourselves. - Aristotle",
        "Happiness is not something ready made. It comes from your own actions. - Dalai Lama",
        "For every minute you are angry you lose sixty seconds of happiness. - Ralph Waldo Emerson",
        "Happiness depends upon ourselves. - Aristotle",
        "Be happy for this moment. This moment is your life. - Omar Khayyam",
        "The purpose of our lives is to be happy. - Dalai Lama",
        "Happiness is the secret to all beauty. There is no beauty without happiness. - Christian Dior",
        "Count your age by friends, not years. Count your life by smiles, not tears. - John Lennon",
        "Think of all the beauty still left around you and be happy. - Anne Frank",
        "The only joy in the world is to begin. - Cesare Pavese",
        "Success is not the key to happiness. Happiness is the key to success. - Albert Schweitzer",
        "Happiness is when what you think, what you say, and what you do are in harmony. - Mahatma Gandhi",
        "The happiest people don’t have the best of everything—they just make the best of everything. - Unknown",
        "The happiness of your life depends upon the quality of your thoughts. - Marcus Aurelius",
        "If you want to be happy, be. - Leo Tolstoy",
        "Happiness is a direction, not a place. - Sydney J. Harris",
        "Most folks are as happy as they make up their minds to be. - Abraham Lincoln",
        "Happiness is a warm puppy. - Charles M. Schulz",
        "Happiness is not by chance, but by choice. - Jim Rohn",
        "Be happy with what you have while working for what you want. - Helen Keller",
        "Let us be grateful to the people who make us happy. - Marcel Proust",
        "Happiness radiates like the fragrance from a flower and draws all good things towards you. - Maharishi Mahesh Yogi",
        "Happiness grows at our own firesides, and is not to be picked in strangers' gardens. - Douglas William Jerrold",
        "The best way to cheer yourself is to try to cheer someone else up. - Mark Twain",
        "Joy is not in things; it is in us. - Richard Wagner",
        "Happy he who learns to bear what he cannot change. - Friedrich Schiller",
        "Happiness held is the seed; happiness shared is the flower. - John Harrigan",
        "To be happy, we must not be too concerned with others. - Albert Camus",
        "Happiness is the art of never holding in your mind the memory of any unpleasant thing that has passed. - Unknown",
        "Happiness is acceptance. - Unknown",
        "The talent for being happy is appreciating and liking what you have, instead of what you don't have. - Woody Allen",
        "Some cause happiness wherever they go; others whenever they go. - Oscar Wilde",
        "Don’t wait around for other people to be happy for you. Any happiness you get you’ve got to make yourself. - Alice Walker",
        "Happiness is not something you postpone for the future; it is something you design for the present. - Jim Rohn",
        "The joy of life consists in the exercise of one's energies, continual growth, constant change, the enjoyment of every new experience. - Aleister Crowley",
        "Happiness is like a kiss. You must share it to enjoy it. - Bernard Meltzer",
        "True happiness arises, in the first place, from the enjoyment of oneself. - Joseph Addison",
        "The secret to happiness is freedom, and the secret to freedom is courage. - Thucydides",
        "Happiness makes up in height for what it lacks in length. - Robert Frost",
        "Of all forms of caution, caution in love is perhaps the most fatal to true happiness. - Bertrand Russell",
        "A happy heart makes a cheerful face. - Proverbs",
        "The grand essentials to happiness in this life are something to do, something to love, and something to hope for. - Allan K. Chalmers",
        "The present moment is filled with joy and happiness. If you are attentive, you will see it. - Thich Nhat Hanh",
        "Happiness is not a goal; it is a by-product. - Eleanor Roosevelt",
        "There is only one happiness in this life, to love and be loved. - George Sand",
        "Happiness is a journey, not a destination. - Ben Sweetland",
        "Whoever is happy will make others happy. - Anne Frank",
        "Doing what you like is freedom. Liking what you do is happiness. - Unknown",
        "The happiest people are the givers, not the takers. - Unknown",
        "A cheerful heart is good medicine. - Proverbs",
        "Happiness often sneaks in through a door you didn’t know you left open. - John Barrymore",
        "Happiness is the meaning and the purpose of life, the whole aim and end of human existence. - Aristotle",
        "Thousands of candles can be lit from a single candle, and the life of the candle will not be shortened. Happiness never decreases by being shared. - Buddha",
        "Joy does not simply happen to us. We have to choose joy and keep choosing it every day. - Henri J.M. Nouwen",
        "The surest way to happiness is to lose yourself in a cause greater than yourself. - Unknown",
        "Spend more time doing what makes you forget about the time. - Charlotte Eriksson",
        "If you want happiness for an hour, take a nap. If you want happiness for a day, go fishing. If you want happiness for a year, inherit a fortune. If you want happiness for a lifetime, help someone else. - Chinese Proverb",
        "If you want to live a happy life, tie it to a goal, not to people or things. - Albert Einstein",
        "An effort made for the happiness of others lifts us above ourselves. - Lydia M. Child",
        "Being happy never goes out of style. - Lilly Pulitzer",
        "Happiness comes in waves. It’ll find you again. - Unknown",
        "The secret of happiness is to admire without desiring. - Carl Sandburg",
        "Happiness comes from contentment. - Dalai Lama",
        "No medicine cures what happiness cannot. - Gabriel García Márquez",
        "Happiness is a choice that requires effort at times. - Aeschylus",
        "The happiest people don't necessarily have the best of everything; they just make the best of everything. - Sam Cawthorn",
        "Learn to let go. That is the key to happiness. - Buddha",
        "Whatever you decide to do, make sure it makes you happy. - Paulo Coelho",
        "If you want others to be happy, practice compassion. If you want to be happy, practice compassion. - Dalai Lama",
        "Happy people plan actions, they don’t plan results. - Dennis Waitley",
        "Sometimes your joy is the source of your smile, but sometimes your smile can be the source of your joy. - Thich Nhat Hanh",
        "True happiness is... to enjoy the present, without anxious dependence upon the future. - Lucius Annaeus Seneca",
        "The most important thing is to enjoy your life—to be happy—it’s all that matters. - Audrey Hepburn",
        "Happiness is not having what you want. It is appreciating what you have. - Unknown",
        "To live is the rarest thing in the world. Most people exist, that is all. - Oscar Wilde",
        "The best way to pay for a lovely moment is to enjoy it. - Richard Bach",
        "One of the secrets of a happy life is continuous small treats. - Iris Murdoch",
        "Take time to make your soul happy. - Unknown",
        "Happiness is found when you stop comparing yourself to other people. - Unknown",
        "Wherever you go, no matter what the weather, always bring your own sunshine. - Anthony J. D'Angelo",
        "A happy life consists in the tranquility of mind. - Cicero",
        "The moments of happiness we enjoy take us by surprise. It is not that we seize them, but that they seize us. - Ashley Montagu",
        "If you aren’t grateful for what you already have, what makes you think you would be happy with more? - Roy T. Bennett",
        "Start each day with a grateful heart. - Unknown",
        "Happiness is a habit—cultivate it. - Elbert Hubbard",
        "The happier you are, the more beautiful you become. - Unknown",
        "One joy scatters a hundred griefs. - Chinese Proverb",
        "Happiness depends more on the inward disposition of mind than on outward circumstances. - Benjamin Franklin",
        "Being happy isn’t having everything in your life be perfect. Maybe it’s about stringing together all the little things. - Ann Brashares",
        "The happiness of life is made up of minute fractions—the little, soon-forgotten charities of a kiss or smile, a kind look or heartfelt compliment. - Samuel Taylor Coleridge",
        "Happiness grows at our own firesides, and is not to be picked in strangers’ gardens. - Douglas William Jerrold",
        "Happiness is the interval between periods of unhappiness. - Don Marquis",
        "Blessed are those who can give without remembering and take without forgetting. - Elizabeth Bibesco",
        "Happiness walks on busy feet. - Kitte Turmell",
        "Happiness is only real when shared. - Christopher McCandless",
        "The essence of philosophy is that a man should so live that his happiness shall depend as little as possible on external things. - Epictetus",
        "Success is getting what you want, happiness is wanting what you get. - W.P. Kinsella",
        "Happiness is the highest good. - Aristotle",
        "A calm and modest life brings more happiness than the pursuit of success combined with constant restlessness. - Albert Einstein",
        "May your choices reflect your hopes, not your fears. - Nelson Mandela",
        "Oftentimes, the happiest people are those who simply have the best attitude about whatever comes their way. - Unknown",
        "Great happiness is to be found not in comfort, but in conquering obstacles. - Zig Ziglar",
        "To be happy, we must be true to nature and carry our age along with us. - Margaret Fuller",
        "Find ecstasy in life; the mere sense of living is joy enough. - Emily Dickinson",
        "The mere sense of living is joy enough. - Emily Dickinson",
        "Happiness is having a large, loving, caring, close-knit family in another city. - George Burns",
        "Nothing can bring you happiness but yourself. - Ralph Waldo Emerson",
        "Let your smile change the world, but don’t let the world change your smile. - Connor Franta",
        "Happiness is contagious—spread a little wherever you go. - Unknown",
        "Smile, and the world smiles with you. - Stanley Gordon West",
        "Happiness is like jam. You can’t spread even a little without getting some on yourself. - Unknown",
        "Don’t let the silly little things steal your happiness. - Unknown",
        "Gratitude is the fairest blossom which springs from the soul. - Henry Ward Beecher",
        "The happiest people take life day by day, complain very little, and are thankful for the little things. - Unknown",
        "Count your blessings, not your problems. - Roy T. Bennett",
        "Sunshine is the best medicine. - Unknown",
    ],
    sad: [
        "Sadness is but a wall between two gardens. - Kahlil Gibran",
        "The pain you feel today is the strength you feel tomorrow. - Unknown",
        "Tears come from the heart and not from the brain. - Leonardo da Vinci"
         "Sadness is but a wall between two gardens. - Kahlil Gibran",
        "The pain you feel today is the strength you feel tomorrow. - Unknown",
        "Tears come from the heart and not from the brain. - Leonardo da Vinci",
        "Even the darkest night will end and the sun will rise. - Victor Hugo",
        "This too shall pass. Pain is temporary, but growth is permanent. - Unknown",
        "Sadness flies away on the wings of time. - Jean de La Fontaine",
        "Every adversity, every heartbreak, carries with it the seed of an equal or greater benefit. - Napoleon Hill",
        "You never know how strong you are until being strong is your only choice. - Bob Marley",
        "Sadness gives depth. Happiness gives height. Sadness gives roots. Happiness gives branches. Both are needed. - Osho",
        "There is no despair so absolute as that which comes with the first moments of our first great sorrow. - George Eliot",
        "Heavy hearts, like heavy clouds in the sky, are best relieved by the letting of a little water. - Christopher Morley",
        "Some people grieve in silence. Sometimes, the only thing they can talk about is the weather. - Unknown",
        "Grief is the price we pay for love. - Queen Elizabeth II",
        "The emotion that can break your heart is sometimes the very one that heals it. - Nicholas Sparks",
        "The walls we build around us to keep sadness out also keep out the joy. - Jim Rohn",
        "Sadness is a natural part of life. Accept it, learn from it, and move on. - Unknown",
        "When you come out of the storm, you won’t be the same person who walked in. That’s what this storm's all about. - Haruki Murakami",
        "Tears are words that the heart can't express. - Unknown",
        "Grief does not change you, Hazel. It reveals you. - John Green",
        "Sometimes, the best way to heal a broken heart is to give it time. - Unknown",
        "Every storm runs out of rain. - Maya Angelou",
        "What brings us to tears will lead us to grace. - Gloria Gaither",
        "The cure for anything is salt water: sweat, tears, or the sea. - Isak Dinesen",
        "Keep your face always toward the sunshine — and shadows will fall behind you. - Walt Whitman",
        "Your sadness is a gift. Like your grief, it is a doorway to your deeper wisdom. - Joanna Macy",
        "Sometimes you have to drown your sorrow to hold onto the happiness. - Unknown",
        "Grief is not as heavy as guilt, but it takes more away from you. - Veronica Roth",
        "Sadness corrodes the heart. Shine your light on the darkness to heal it. - Unknown",
        "The deeper that sorrow carves into your being, the more joy you can contain. - Khalil Gibran",
        "Sorrow prepares you for joy. It violently sweeps everything out of your house, so that new joy can find space to enter. - Rumi",
        "Don’t grieve. Anything you lose comes round in another form. - Rumi",
        "Sadness is an ocean, and sometimes we just need to float. - Unknown",
        "When you feel like giving up, remember why you held on for so long in the first place. - Unknown",
        "Pain nourishes courage. You can’t be brave if you’ve only had wonderful things happen to you. - Mary Tyler Moore",
        "The sadness will eventually run its course. Give it time and be gentle with yourself. - Unknown",
        "A sad soul can kill you quicker than a germ. - John Steinbeck",
        "Sometimes tears are the language of pain we don’t know how to express. - Unknown",
        "No matter how you feel, get up, dress up, show up, and never give up. - Regina Brett",
        "In the middle of winter, I found there was, within me, an invincible summer. - Albert Camus",
        "Every tear teaches us something. - Paulo Coelho",
        "Sadness is but the shadow of joy. - Unknown",
        "Crying is how your heart speaks when your lips can’t explain the pain you feel. - Unknown",
        "Turn your wounds into wisdom. - Oprah Winfrey",
        "No sad story was ever ended with ‘and they lived happily ever after’ without first overcoming troubles. - Unknown",
        "There is a time for departure, even when there's no certain place to go. - Tennessee Williams",
        "The walls we build to protect ourselves also keep out the light. - Unknown",
        "Some days require volume control. - Unknown",
        "Sorrow is one of the vibrations that prove the fact of living. - Antoine de Saint-Exupéry",
        "There are some wounds that never show on the body that are deeper and more hurtful than anything that bleeds. - Laurell K. Hamilton",
        "Heal your pain by embracing it, not avoiding it. - Unknown",
        "Pain is inevitable, suffering is optional. - Haruki Murakami",
        "To weep is to make less the depth of grief. - William Shakespeare",
        "When sadness overwhelms, it is also an opportunity to grow. - Unknown",
        "The soul would have no rainbow if the eyes had no tears. - Native American Proverb",
        "Healing takes courage, and we all have courage, even if we have to dig a little to find it. - Tori Amos",
        "Sometimes laughter is the best medicine for a heavy heart. - Unknown",
        "Let your tears water the seeds of new beginnings. - Unknown",
        "Sadness is the silent sister of joy. - Unknown",
        "The worst kind of sad is not being able to explain why. - Unknown",
        "Behind every beautiful thing, there is some kind of pain. - Bob Dylan",
        "We must understand that sadness is an ocean, and sometimes we drown, while other days we are forced to swim. - R.M. Drake",
        "There are moments when I wish I could roll back the clock and take all the sadness away, but I have the feeling that if I did, the joy would be gone as well. - Nicholas Sparks",
        "Never make someone a priority when all you are to them is an option. - Maya Angelou",
        "When you're happy, you enjoy the music but when you're sad, you understand the lyrics. - Frank Ocean",
        "Forgive me, for all the things I did but mostly for the ones that I did not. - Donna Tartt",
        "I always like walking in the rain, so no one can see me crying. - Charlie Chaplin",
        "First, accept sadness. Realize that without losing, winning isn't so great. - Alyssa Milano",
        "Maybe we all have darkness inside of us and some of us are better at dealing with it than others. - Jasmine Warga",
        "A million words would not bring you back, I know because I tried, neither would a million tears, I know because I cried. - Unknown",
        "Things change. And friends leave. Life doesn't stop for anybody. - Stephen Chbosky",
        "Breathing is hard. When you cry so much, it makes you realize that breathing is hard. - David Levithan",
        "You cannot protect yourself from sadness without protecting yourself from happiness. - Jonathan Safran Foer",
        "There is one pain, I often feel, which you will never know. It's caused by the absence of you. - Ashleigh Brilliant",
        "When you think you’re first falling in love, just then you realize you’re falling out of love. - David Grayson",
        "Since I can’t be with you right now I will have to be content just dreaming about when we will be together again. - Susan Polis Schutz",
        "Falling in love is like holding a candle. Initially, it lightens up the world around you. Then it starts melting and hurts you. Finally, it goes off and everything is darker than ever, and all you are left with is the… BURN! - Syed Arshad",
        "I wonder if I could take back every ‘I love you’ ever said to you, would I do it? - Anaïs Nin",
        "Love never dies a natural death. It dies because we don’t know how to replenish its source. It dies of blindness and errors and betrayals. It dies of illness and wounds; it dies of weariness, of withering, of tarnishing. - Alfred Lord Tennyson",
        "Tis better to have loved and lost than never to have loved at all. - Alfred Lord Tennyson",
        "The walls we build around us to keep sadness out also keep out the joy. - Jim Rohn",
        "There is a time for departure, even when there’s no certain place to go. - Tennessee Williams",
        "You call me up again just to break me like a promise. - Taylor Swift",
        "You know, a heart can be broken, but it keeps on beating, just the same. - Fannie Flagg",
        "Would it be the same if I saw you in heaven? - Eric Clapton",
        "We loved with a love that was more than love. - Edgar Allan Poe",
        "There are all kinds of love in this world but never the same love twice. - F. Scott Fitzgerald",
        "Our greatest joy and our greatest pain come in our relationships with others. - Stephen R. Covey",
        "Relationships are like glass. Sometimes it’s better to leave them broken than try to hurt yourself putting it back together. - Unknown",
        "It is sad not to love, but it is much sadder not to be able to love. - Miguel de Unamuno",
        "Some people are going to leave, but that’s not the end of your story. That’s the end of their part in your story. - Faraaz Kazi",
        "It’s amazing how someone can break your heart and you can still love them with all the little pieces. - Ella Harper"
    ],
    angry: [
        "Anger is one letter short of danger. - Eleanor Roosevelt",
        "The greatest remedy for anger is delay. - Lucius Annaeus Seneca",
        "Anger is a momentary madness, so control your passion or it will control you. - G. M. Trevelyan"
    ],
    inspired: [
        "The best way to predict the future is to create it. - Peter Drucker",
        "Inspiration exists, but it has to find you working. - Pablo Picasso",
        "The only way to do great work is to love what you do. - Steve Jobs"
    ],
    confident: [
        "Confidence is preparation. Everything else is beyond your control. - Richard Kline",
        "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. - Christian D. Larson",
        "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer"
    ],
    anxious: [
        "Do not anticipate trouble, or worry about what may never happen. Keep in the sunlight. - Benjamin Franklin",
        "Anxiety is a thin stream of fear trickling through the mind. If encouraged, it cuts a channel into which all other thoughts are drained. - Arthur Somers Roche",
        "Nothing in the affairs of men is worthy of great anxiety. - Plato"
    ],
    hopeful: [
        "Hope is being able to see that there is light despite all of the darkness. - Desmond Tutu",
        "The darkest hour has only sixty minutes. - Morris Mandel",
        "Hope is a waking dream. - Aristotle"
    ]
};

// Function to display the quote
function getQuote(emotion) {
    const quoteArray = quotes[emotion];
    const randomQuote = quoteArray[Math.floor(Math.random() * quoteArray.length)];
    
    const quoteDisplay = document.getElementById("quote");

    // Add fade-out effect before displaying the new quote
    quoteDisplay.classList.add("fade-out");
    setTimeout(() => {
        quoteDisplay.innerText = randomQuote;
        quoteDisplay.classList.remove("fade-out");
    }, 500);
}



